_target_: src.models.diffusion.Diffusion
beta_schedule: linear
beta_start: 0.0001
beta_end: 0.02
t_min: 10
t_max: 1000
diffusion_ind_length: 32
noise_std: 0.05
aug: no
ada_maxp: null
ts_dist: priority
