_target_: src.models.SpectralNormACGAN
lambda_aux_loss: 0.5
lr: 0.0001
output_dir: ${paths.output_dir}
loss_type: wasserstein
disc_iters: 5
generator:
  _target_: src.models.sn_gan.ConditionalGenerator
  latent_dim: 100
  channels: 3
  img_size: 32
  n_classes: 10
discriminator:
  _target_: src.models.sn_gan.ConditionalDiscriminator
  channels: 3
  img_size: 32
  n_classes: 10
