_target_: src.models.SpectralNormGAN
generator:
  _target_: src.models.sn_gan.Generator
  channels: 1
  latent_dim: 100
  img_size: 28
discriminator:
  _target_: src.models.sn_gan.Discriminator
  channels: 1
lr: 0.0001
output_dir: ${paths.output_dir}
loss_type: wasserstein
disc_iters: 5
