_target_: src.models.VanillaGAN
lr: 0.0001
output_dir: ${paths.output_dir}
generator:
  _target_: src.models.Generator
  channels: 1
  img_size: 28
  latent_dim: 100
discriminator:
  _target_: src.models.Discriminator
  channels: 1
  img_size: 28
