_target_: src.models.WACGAN_GP
disc_iters: 5
lambda_term: 10
lr: 0.0001
lambda_aux_loss: 0.5
output_dir: ${paths.output_dir}
generator:
  _target_: src.models.vanilla_acgan.ConditionalGenerator
  latent_dim: 100
  channels: 3
  img_size: 32
  n_classes: 10
discriminator:
  _target_: src.models.vanilla_acgan.ConditionalDiscriminator
  channels: 3
  img_size: 32
  n_classes: 10
