_target_: src.models.WGAN_GP
critic_iter: 5
lambda_term: 10
output_dir: ${paths.output_dir}
lr: 0.0001
generator:
  _target_: src.models.wgan.Generator
  channels: 1
  latent_dim: 100
discriminator:
  _target_: src.models.wgan.Discriminator
  channels: 1
