_target_: src.models.WGAN_GP
critic_iter: 5
lambda_term: 10
lr: 0.0001
output_dir: ${paths.output_dir}
generator:
  _target_: src.models.wgan.Generator
  channels: 3
  latent_dim: 100
discriminator:
  _target_: src.models.wgan.Discriminator
  channels: 3
